/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mob1023_lab03;

import java.awt.event.KeyAdapter;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuanc
 */
public class Lab03 extends javax.swing.JFrame {
    StudentList stl = new StudentList();
    String headers[] = {"Họ và tên", "Điểm số", "Chuyên ngành", "Học lực", "Thưởng"};
    DefaultTableModel model = new DefaultTableModel(headers, 0);
    
    /**
     * Creates new form Lab03
     */
    public Lab03() {
        initComponents();
        tblStudents.setModel(model);
        tblStudents.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtMark = new javax.swing.JTextField();
        cbMajor = new javax.swing.JComboBox<>();
        txtGrade = new javax.swing.JTextField();
        chkGift = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnArrName = new javax.swing.JButton();
        btnArrScore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Sinh Viên");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        jLabel2.setText("Họ và tên: ");

        jLabel3.setText("Điểm:");

        jLabel4.setText("Ngành:");

        jLabel5.setText("Học lực:");

        txtMark.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMarkKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMarkKeyTyped(evt);
            }
        });

        cbMajor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thiết kế đồ họa", "Lập trình di động", "Thiết kế trang web", "Ứng dụng phần mềm" }));

        txtGrade.setEditable(false);

        chkGift.setText("Có phần thưởng?");

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudents);

        btnAdd.setText("Thêm");
        btnAdd.setPreferredSize(new java.awt.Dimension(90, 25));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Cập nhật");
        btnUpdate.setPreferredSize(new java.awt.Dimension(90, 25));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnRemove.setText("Xóa");
        btnRemove.setPreferredSize(new java.awt.Dimension(90, 25));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnNew.setText("Nhập mới");
        btnNew.setPreferredSize(new java.awt.Dimension(90, 25));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnArrName.setText("Sắp xếp theo họ và tên");
        btnArrName.setPreferredSize(new java.awt.Dimension(180, 25));
        btnArrName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArrNameActionPerformed(evt);
            }
        });

        btnArrScore.setText("Sắp xếp theo điểm số");
        btnArrScore.setPreferredSize(new java.awt.Dimension(180, 25));
        btnArrScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArrScoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkGift)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName)
                                    .addComponent(txtMark)
                                    .addComponent(cbMajor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtGrade))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnArrScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnArrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkGift)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArrScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(txtMark.getText().length() == 0 || Double.parseDouble(txtMark.getText()) > 10.0 || Double.parseDouble(txtMark.getText()) < 0.0){
            JOptionPane.showMessageDialog(this, "Điểm không hợp lệ!", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        } else{
            Student st = new Student();
            
            st.setName(txtName.getText());
            st.setScore(Double.parseDouble(txtMark.getText()));
            st.setMajor(cbMajor.getSelectedItem().toString());
            st.setGrade(getGrade(Double.parseDouble(txtMark.getText())));
            if(chkGift.isSelected()){
                st.setGift(true);
            } else{
                st.setGift(false);
            }
            
            add(st);
            loadTable();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtMarkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarkKeyTyped
        // TODO add your handling code here:
        txtMark.addKeyListener(new KeyAdapter() {});
        char char_input = evt.getKeyChar();
        if (((char_input < '0') || (char_input > '9')) && (char_input != '\b') && (char_input != '.'))
        {
            JOptionPane.showMessageDialog(this, "Chỉ được nhập số!", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
            txtMark.setText("");
            evt.consume();
        }
    }//GEN-LAST:event_txtMarkKeyTyped

    private void txtMarkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarkKeyReleased
        // TODO add your handling code here:
        if(txtMark.getText().length() != 0){
            txtGrade.setText(getGrade(Double.parseDouble(txtMark.getText())));
        }
    }//GEN-LAST:event_txtMarkKeyReleased

    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked
        // TODO add your handling code here:
        int r = tblStudents.getSelectedRow();
        txtName.setText(tblStudents.getValueAt(r, 0).toString());
        txtMark.setText(tblStudents.getValueAt(r, 1).toString());
        cbMajor.setSelectedItem(tblStudents.getValueAt(r, 2).toString());
        txtGrade.setText(tblStudents.getValueAt(r, 3).toString());
        if(tblStudents.getValueAt(r, 4).toString().equalsIgnoreCase("Có")){
            chkGift.setSelected(true);
        } else{
            chkGift.setSelected(false);
        }
    }//GEN-LAST:event_tblStudentsMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if(txtMark.getText().length() != 0 && tblStudents.getSelectedRow() != -1){
            int r = tblStudents.getSelectedRow();
            stl.stl.get(r).setName(txtName.getText());
            stl.stl.get(r).setScore(Double.parseDouble(txtMark.getText()));
            stl.stl.get(r).setMajor(cbMajor.getSelectedItem().toString());
            stl.stl.get(r).setGrade(txtGrade.getText());
            if(chkGift.isSelected()){
                stl.stl.get(r).setGift(true);
            } else{
                stl.stl.get(r).setGift(false);
            }
            
            loadTable();
        } else{
            JOptionPane.showMessageDialog(this, "Điểm không hợp lệ hoặc chưa chọn dòng cần sửa!", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }    
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        if(stl.check()){
            JOptionPane.showMessageDialog(this, "Danh sách rỗng!", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        } else{
            if(tblStudents.getSelectedRow() != -1){
                int r = tblStudents.getSelectedRow();
                stl.stl.remove(r);
                loadTable();
            } else{
                JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần xóa!", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
            }    
        } 
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtMark.setText("");
        cbMajor.setSelectedItem("Thiết kế đồ họa");
        txtGrade.setText("");
        chkGift.setSelected(false);
        tblStudents.clearSelection();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnArrScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArrScoreActionPerformed
        // TODO add your handling code here:
        if(stl.check()){
            JOptionPane.showMessageDialog(this, "Danh sách rỗng!", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        } else{
            stl.sortByScore();
            loadTable();
            JOptionPane.showMessageDialog(this, "Sắp xếp hoàn tất!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnArrScoreActionPerformed

    private void btnArrNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArrNameActionPerformed
        // TODO add your handling code here:
        if(stl.check()){
            JOptionPane.showMessageDialog(this, "Danh sách rỗng!", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        } else{
            stl.sortByName();
            loadTable();
            JOptionPane.showMessageDialog(this, "Sắp xếp hoàn tất!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnArrNameActionPerformed

    public String getGrade(double score){
        String result;
        
        if(score >= 9){
            result = "Xuất sắc";
        } else if(score >= 8){
            result = "Giỏi";
        } else if(score >= 6.5){
            result = "Khá";
        } else if(score >= 5){
            result = "Trung bình";
        } else{
            result = "Yếu";
        }
        
        return result;
    }
    
    public void loadTable(){
        model.setRowCount(0);
        Object rowData[] = new Object[5];
        for(int i = 0; i < stl.stl.size(); i++){
            rowData[0] = stl.stl.get(i).getName();
            rowData[1] = stl.stl.get(i).getScore();
            rowData[2] = stl.stl.get(i).getMajor();
            rowData[3] = stl.stl.get(i).getGrade();
            if(stl.stl.get(i).isGift()){
                rowData[4] = "Có";
            } else{
                rowData[4] = "Không";
            }
            model.addRow(rowData);
        }
    }
        
    public void add(Student st){
        stl.them(st);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnArrName;
    private javax.swing.JButton btnArrScore;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbMajor;
    private javax.swing.JCheckBox chkGift;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtMark;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
